name: hugo
proxy:
  node:
    - hugo.lndo.site:1313
excludes:
  - node_modules
services:
  node:
    type: node:14
    cmd: >-
      hugo server
        --bind 0.0.0.0
        --navigateToChanged
        --templateMetrics
        --buildDrafts
    ssl: true
    sslExpose: true
    port: 1313
    scanner: false
    build_as_root:
      - curl -SL https://github.com/gohugoio/hugo/releases/download/v0.86.1/hugo_0.86.1_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar -xzf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/local/bin/
      - rm -rf /tmp/* 
tooling:
  yarn:
    service: node
  node:
    service: node
  hugo:
    service: node
    cmd: /usr/local/bin/hugo
  watch:
    service: node
    cmd: yarn run dev

