name: hugo
proxy:
  hugo:
    - hugo.lndo.site:1313
excludes:
  - node_modules
services:
  hugo:
    type: compose
    webroot: .
    # app_mount: delegated
    scanner: false
    ssl: true
    sslExpose: true
    port: 1313
    build:
      - mkdir -p $HOME/src
      - cd $HOME/src && git clone https://github.com/gohugoio/hugo.git
      - cd $HOME/src/hugo && go install --tags extended
    services:
      image: golang:1.17.0-bullseye
      environment:
        CGO_ENABLED: 1
      # Required. See Below
      # ports:
      #   - '1313:1313'
      command: app
tooling:
  yarn:
    service: hugo
  node:
    service: hugo
  hugo:
    service: hugo
  watch:
    service: go
    cmd: yarn run dev
  serve:
    service: hugo
    cmd: hugo server --bind 0.0.0.0 --navigateToChanged --templateMetrics --buildDrafts --disableFastRender
